{% set name = "libsass" %}
{% set version = "0.19.2" %}
{% set sha256 = "cb50f385117535f7671ac7ff3144c1ef0b8e088778c58d269ce6f31b87bfad72" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sass/{{ name }}-python/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - pysassc = pysassc:main
    - sassc = sassc:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  skip: True  # [win and py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - six

  run:
    - python
    - six

test:
  imports:
    - sass
  commands:
    - sassc --help
    - pysassc --help

about:
  home: https://github.com/dahlia/libsass-python
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: 'A straightforward binding of libsass for Python. Compile Sass/SCSS in Python with no Ruby stack at all!'
  description: |
    This package provides a simple Python extension module sass which is binding 
    Libsass (written in C/C++ by Hampton Catlin and Aaron Leung). It's very 
    straightforward and there isn't any headache related Python distribution/deployment.
  doc_url: https://hongminhee.org/libsass-python/
  dev_url: https://github.com/dahlia/libsass-python

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - isuruf
    - marcelotrevisani
