travis:
  secure:
    BINSTAR_TOKEN: qQJ5hwJkKZaMipdVfkcf1pNPP3xnwq329I5TUn22mEMKPKbq1MNkySzIPMogsGnTyob5ipxRM7LWRgQ6CNDhXIKqJZEmygrmHSjqxwnl25fm7KUzTyX4v0gg+b2p3yicBbUf9/GCb6jiLzvqkT3lxR0CKVaoGG2rx7t8G//rERhVo6DbvnX9v7xdiOEAiMu3sk3mHgZ1WQcgsMRw67j3cooZG7A05xb47E4jw8Fd2SSBFioEmQhZjfm2jvsgRH3ZAeB3oXo0i7apDOUnPWGv8MQ6Z4bg4qfwLNpz+MVV7crKSZNSiLuDRWDqsovr6f3EaFy4EZUECOo2yEY0/dreTiYBotWqW0xBHoDI4+8UYx7MepIB6LkDPIGAOgbvopR2zgDicL361tmBDCYX1z9XZ99PtbtZKXShfAfFMhN1XeLHZT0ipzxEsZKk3jAALgRa/6nTskaM2pnOu2xltl72oAYj0M1OWV3tVJQufzlHwgv0c7hN/iknzUuz4EM0IIVZtX4vMBMds0Y+f+GWl4ATuHbJNUfOB8a1UsgYOaB/2IvoHJvhKYJH3XcpLXG2WbMhvzGgV3CenEaiGGjpfmFaM5KHAfKya8JdNoNoEHEmzOYN89MS7xzvKrbehZC0kyT6CjqFBE92XWhEH5ogpEr0HHIwSiE6XuU1K5PFYu1FbuU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
